### ISSUE TITLE
Separar atividades planejadas nas milestones até a R2

### ISSUE THREAD

**Issue by lucasca73** [fga-eps-mds/2018.2-Integra-Vendas#267]
Separando as atividades teremos uma visão mais completa do roadmap até a R2.

**Tarefas**
- [x] Separar atividades para Sprint 11
- [x] Separar atividades para Sprint 12
- [x] Separar atividades para Sprint 13
- [x] Separar atividades para Sprint 14 (Pré-Release 2)
- [x] Separar atividades para Sprint 15 (Release 2)

**Comment by lucasca73** [comment]
As sprints 13 e 14 estão preparadas para solucionar eventuais problemas.
